# -*- coding: utf-8 -*-
"""Analise de Dados Pedala Recife

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Dr8Bw-D96xxXsM3LtbJUTxRt9l4l8S3

🚲 **Projeto: Análise das Estações de Bike Alugadas no Recife**

**Autora:** Patrícia Cavalcanti Alves

🎓 **Formação Acadêmica**  

- Graduada em Bacharelado em Administração: Unit - Centro Universitário Tiradentes
- Pós Graduando em Ciência de Dados e IA: Faculdade Senac

📌 **Contexto**

Atualmente, a cidade do Recife possui cerca de 227 km de ciclovias, ciclofaixas e ciclorrotas.
Segundo dados georreferenciados, são 193 km de rotas permanentes e 34 km de rotas operacionais (funcionam em domingos e feriados).

Esse cenário incentiva o uso de bicicletas como meio de transporte, promovendo:

✅ Mobilidade urbana sustentável

✅ Redução de poluentes

✅ Melhora da saúde da população

Além disso, o programa de aluguel de bikes tem mostrado grande potencial. A distribuição das estações nos bairros é um ponto-chave para atender melhor à população.

📊 **Análise de Dados**
1. Importação das bibliotecas e dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
# Carregar dataset de estações de bikes
df_bike = pd.read_csv(
    "http://dados.recife.pe.gov.br/dataset/7fac73fa-c0bb-4bae-9c21-2a45b82016a2/resource/e6e4ac72-ff15-4c5a-b149-a1943386c031/download/estacoesbike.csv",
    sep=";"
)

df_bike.head()

"""2. Limpeza e ajustes no DataFrame"""

# Remover apenas colunas que não vamos usar
df_bike = df_bike.drop(columns=['codigo', 'nome'])

# Renomear colunas para facilitar leitura
df_bike.rename(columns={
    'localizacao': 'endereco',
    'capacidade': 'quant_bikes'
}, inplace=True)

df_bike.info()

"""3. Distribuição de bikes por bairro"""

# Agrupar total de bikes por bairro
bairros_bikes = df_bike.groupby('bairro')['quant_bikes'].sum().reset_index()

# Ordenar por quantidade de bikes (descendente)
bairros_bikes_sorted = bairros_bikes.sort_values(by='quant_bikes', ascending=False)

bairros_bikes_sorted.head(10)

"""4. Visualização: Top 20 bairros com mais bikes"""

plt.figure(figsize=(20, 8))
sns.barplot(x='bairro', y='quant_bikes', data=bairros_bikes_sorted.head(20), palette='Blues_d')

plt.title('Top 20 Bairros com Maior Quantidade de Bikes', fontsize=16)
plt.xlabel('Bairros', fontsize=14)
plt.ylabel('Total de Bikes', fontsize=14)
plt.xticks(rotation=45)

# Adicionar valores no topo das barras
for i, v in enumerate(bairros_bikes_sorted.head(20)['quant_bikes']):
    plt.text(i, v + 0.5, str(v), ha='center', fontsize=10)

plt.tight_layout()
plt.show()

"""5. Mapa Interativo das Estações"""

mapa = folium.Map(location=[-8.05, -34.9], zoom_start=12)

for _, row in df_bike.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"Bairro: {row['bairro']}<br>Bikes: {row['quant_bikes']}",
        icon=folium.Icon(color="blue", icon="bicycle", prefix="fa")
    ).add_to(mapa)

mapa